from typing import Protocol
from safemeal.modules.knowledge.contracts.ingestion import IngestionJob


class IngestionQueue(Protocol):
    async def enqueue(self, job: IngestionJob) -> None: ...
    async def dequeue(self, timeout_seconds: int = 5) -> IngestionJob | None: ...
    async def update(self, job: IngestionJob) -> None: ...
    async def get(self, job_id: str) -> IngestionJob | None: ...
