"""Validated contract for recipes generated by a language model."""

from __future__ import annotations

from decimal import Decimal
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from safemeal.modules.dietary_safety.domain import ingredient_matches_forbidden_term
from safemeal.modules.recipe_catalog.models import (
    DietaryType,
    NonBlankText,
    NutritionInfo,
    RecipeDifficulty,
    normalize_quantity,
)


GeneratedUnit = Literal["mg", "g", "kg", "ml", "l", "茶匙", "汤匙", "个", "条"]


class RecipeGenerationRequest(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

    requirements: str = Field(min_length=1, max_length=5000)
    include_ingredients: tuple[str, ...] = Field(default_factory=tuple, max_length=20)
    exclude_ingredients: tuple[str, ...] = Field(default_factory=tuple, max_length=50)
    dietary_types: tuple[DietaryType, ...] = Field(default_factory=tuple, max_length=3)
    servings: int | None = Field(default=None, ge=1, le=100)
    max_total_time_minutes: int | None = Field(default=None, ge=1, le=24 * 60)

    @field_validator("include_ingredients", "exclude_ingredients", mode="before")
    @classmethod
    def normalize_ingredient_terms(cls, value: object) -> object:
        if value is None:
            return ()
        if not isinstance(value, (list, tuple, set)):
            raise ValueError("ingredient constraints must be a list or tuple")
        return tuple(
            dict.fromkeys(str(item).strip() for item in value if str(item).strip())
        )


class GeneratedIngredient(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

    name: NonBlankText
    quantity: Decimal = Field(gt=0)
    unit: GeneratedUnit
    preparation: str | None = Field(default=None, max_length=255)
    category: str | None = Field(default=None, max_length=100)

    @model_validator(mode="after")
    def validate_quantity_unit(self) -> "GeneratedIngredient":
        normalize_quantity(self.quantity, self.unit)
        return self


class GeneratedCookingStep(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

    number: int = Field(ge=1)
    action: NonBlankText
    instruction: NonBlankText
    duration_minutes: int = Field(default=0, ge=0, le=24 * 60)
    temperature: str | None = Field(default=None, max_length=100)
    tips: str | None = Field(default=None, max_length=1000)


class GeneratedRecipe(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

    name: NonBlankText
    description: str = Field(min_length=1, max_length=2000)
    total_time_minutes: int = Field(ge=1, le=24 * 60)
    servings: int = Field(ge=1, le=100)
    difficulty: RecipeDifficulty
    cuisine: str | None = Field(default=None, max_length=255)
    ingredients: tuple[GeneratedIngredient, ...] = Field(min_length=1, max_length=100)
    steps: tuple[GeneratedCookingStep, ...] = Field(min_length=1, max_length=100)
    nutrition: NutritionInfo
    allergens: tuple[str, ...] = Field(default_factory=tuple, max_length=50)
    dietary_types: tuple[DietaryType, ...] = Field(default_factory=tuple, max_length=3)

    @model_validator(mode="after")
    def validate_recipe_shape(self) -> "GeneratedRecipe":
        names = [item.name.casefold() for item in self.ingredients]
        if len(names) != len(set(names)):
            raise ValueError("generated recipe contains duplicate ingredients")
        numbers = [step.number for step in self.steps]
        if numbers != list(range(1, len(numbers) + 1)):
            raise ValueError("generated recipe steps must be contiguous from 1")
        return self

    def contains_any(self, terms: tuple[str, ...]) -> bool:
        return any(
            ingredient_matches_forbidden_term(ingredient.name, term)
            for ingredient in self.ingredients
            for term in terms
        )


def is_recipe_generation_request(question: str) -> bool:
    normalized = question.casefold()
    recipe_terms = ("菜谱", "食谱", "配方", "一道菜")
    generation_terms = ("生成", "设计", "创作", "制定", "原创", "新菜")
    return any(term in normalized for term in recipe_terms) and any(
        term in normalized for term in generation_terms
    )


__all__ = [
    "GeneratedCookingStep",
    "GeneratedIngredient",
    "GeneratedRecipe",
    "GeneratedUnit",
    "RecipeGenerationRequest",
    "is_recipe_generation_request",
]
